// NextJS
import type { Metadata } from "next";
import { IBM_Plex_Sans, Instrument_Serif } from "next/font/google";
// CSS
import "./globals.css";
// DNS
import dns from 'node:dns';
dns.setServers(['1.1.1.1', '8.8.8.8']);
// Components
import AuthSessionProvider from '@/components/providers/SessionProvider'
import Navigation from "@/components/navigation/Navigation";
import Footer from "@/components/footer/Footer";
import HWContainer from "@/components/layout/HWContainer";

const instrumentSarif = Instrument_Serif({
  variable: "--font-instrument-sarif",
  weight: "400",
  subsets: ["latin"],
});

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${instrumentSarif.variable} ${ibmPlexSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navigation />
        <AuthSessionProvider>
          <HWContainer>
            {children}
          </HWContainer>
        </AuthSessionProvider>
        <Footer />
      </body>
    </html>
  );
}
